config/routes.rb
Rails.application.routes.draw do

  resources :groups do
	resources :comments do
		match 'bookpage/:bookpage', to: 'comments#bookpage', via: 'get', on: :collection, as: :page
	end
  end

  resources :user_groups, only: [:create, :destroy, :edit, :update]
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root 'static_pages#home'

  match '/help',    to: 'static_pages#help',    via: 'get'

  match '/about',   to: 'static_pages#about',   via: 'get'

  match '/contact', to: 'static_pages#contact', via: 'get'
  
  match '/signup',  to: 'users#new',            via: 'get'

  match '/signin',  to: 'sessions#new',		via: 'get'

  match '/signout', to: 'sessions#destroy', 	via: 'delete'
  post  'modal' => 'user_groups#modal'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :group
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
  validates :page_number,  presence: true, numericality: { greater_than: 0 }
  validate  :page_number_less_than_total_pages

  def page_number_less_than_total_pages
	unless group.present? && page_number.present? && page_number <= group.page_number
		errors.add(:page_number, '^Comment page number exceeds book number of pages!')
	end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  #before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :correct_group_user, only: [:edit, :update, :destroy, :create, :new]
  before_action :correct_commenter, only: [:update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    if params.has_key?(:group_id)
	@group = Group.find(params[:group_id])
	@comments = @group.comments
    else
    	@comments = Comment.all
    end
  end

  def bookpage
	if params.has_key?(:group_id) && params.has_key?(:bookpage)
		@group = Group.find(params[:group_id])
		@current_comment_page = params[:bookpage]
		@comments = @group.comments.where( 'page_number in (?)',params[:bookpage] )
		@comment = @group.comments.build
		@next_page = nil
		@prev_page = nil
		if Integer(params[:bookpage]) <= @group.page_number
			@next_page = Integer(params[:bookpage]) + 1
		end

		if Integer(params[:bookpage]) > 1
			@prev_page = Integer(params[:bookpage]) - 1
		end
	else
		redirect_to groups_path, notice: "How did you get there?"
	end
  end
  # GET /comments/1
  # GET /comments/1.json
  def show
	if params.has_key?(:group_id)
		group = Group.find(params[:group_id])
		@comment = group.comments.find( params[:id] )
	else
		@comment = Comment.find( params[:id] )
	end
  end

  # GET /comments/new
  def new
	if params.has_key?(:group_id)
		group = Group.find(params[:group_id])
		@comment = group.comments.build
	else
		@comment = Comment.new
	end
  end

  # GET /comments/1/edit
  def edit
	group = Group.find(params[:group_id])
	@comment = group.comments.find(params[:id])	
  end

  # POST /comments
  # POST /comments.json
  def create
    group = Group.find(params[:group_id])
    @comment = group.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to [@comment.group, @comment], notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    group = Group.find( params[:group_id] )
    @comment = group.comments.find(params[:id])
    respond_to do |format|
      if @comment.update_attributes(comment_params)
        format.html { redirect_to [@comment.group, @comment], notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    group = Group.find( params[:group_id] )
    @comment = group.comments.find(params[:id])
    @comment.destroy
    flash[:success] = "Comment deleted successfully"
    respond_to do |format|
      format.html { redirect_to group_comments_url }
      format.json { head :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:title, :body , :user_id, :page_number)
    end

    def correct_group_user
	unless signed_in?
		store_location
		redirect_to signin_url, notice: "Please sign in."
		return
	end

	if params.has_key?(:group_id)
		unless current_user.group_ids.include? params[:group_id].to_i
			store_location
			redirect_to group_path(params[:group_id]), notice: "You must be a member of this group first"
			return
		end
        else
		redirect_to user_path(current_user), notice: "Wrong path!" 
	end

    end

    def correct_commenter
	group = Group.find( params[:group_id] )
    	@comment = group.comments.find(params[:id])
	unless @comment.user_id == current_user.id
		redirect_to group_path(group.id), notice: "You are not allowed to do that"
	end
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<div class="row">
 <div class="span5">
<h3>New comment</h3>

<%= form_for([@comment.group,@comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
     <div class="alert alert-error">
      The form contains <%= pluralize(@comment.errors.count, "error") %>.
     </div>
      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
	<%= f.label :page_number, "Comment for page" %>
	<% unless @current_comment_page.present? %>
		<% @current_comment_page = 1 %>
	<% end %>
			
	<%= f.number_field :page_number, value: @current_comment_page, class: "span2" %>
  </div>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8 %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit "Create", class: "btn" %>
  </div>
<% end %>

 </div>
</div>

app/views/comments/_page_control.html.erb
<div class="row">
	<div class="span1 offset2">
		<% if !@prev_page.nil? %>
			<%= link_to '<',page_group_comments_url(group_id: @group.id, bookpage: @prev_page ), class: "btn btn-small btn-default"%>
		<% end %>
	</div>
	<div class="span1 offset6">
		<% if !@next_page.nil? %>
			<%= link_to '>',page_group_comments_url(group_id: @group.id, bookpage: @next_page ), class: "btn btn-small btn-default"%>
		<% end %>
	</div>
</div>

app/views/comments/_show_comments.html.erb
<div class="row">
  <div class="span8 offset2">
<% unless comments.empty? %>
		<h3>
		<% if Group.find(comments.first.group_id).comments.count > comments.size %>
			Last
		<% end %>
		<%= pluralize(comments.size, 'comment') %></h3>
		<div id="comments">
		<% comments.each  do |comment|%>
			<div class="comment" data-time="<%= comment.created_at.to_i %>" >
				<strong><%= comment.title%> </strong>
				<em>on page: <%= comment.page_number %></em>
				<%= simple_format comment.body %>
				<strong>
				<% if User.where(id: comment.user_id).count > 0 %>
					<%= User.find(comment.user_id).login %>
				<% else %>
					An unlucky deleted user
				<% end %>
				</strong> wrote:
				<span class="dateandoptions">
				<em>on <%= comment.created_at.strftime('%b %d, %Y at %I:%M %p')%></em>
				</span>
				<br>
				<% if signed_in? && current_user.id == comment.user_id%>
					<%= link_to 'Edit', edit_group_comment_path(comment.group, comment) %> |
					<%= link_to 'Delete', group_comment_path(comment.group, comment), method: :delete %>

				<% end %>

			</div>
		<% end %>
		</div>
		<% end %>
  </div>
</div>

app/views/comments/bookpage.html.erb
<h1>Listing comments</h1>

<%= link_to 'Back to group', @group, class: "btn btn-primary" %>
<%= render 'page_control' %>
<%= render 'show_comments', comments: @comments %>
<%= render 'page_control' %>
<%= render 'form' %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', [@comment.group, @comment] %> |
<%= link_to 'Back', group_comments_path(@comment.group) %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<%= render 'show_comments', comments: @comments %>
<br>
<% @comment = @group.comments.build %>
<%= render 'form' %>
<!-- %= link_to 'New Comment', new_group_comment_path, class: "btn" % -->
<%= link_to 'Back to group page', group_path(@group.id) %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', group_comments_path(@comment.group) %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>
<p>
	<strong>Page:</strong>
	<%= @comment.page_number %>
</p>
</p>
<p>
  <strong>Title:</strong>
  <%= @comment.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user.login %>
</p>

<%= link_to 'Edit', edit_group_comment_path(@comment.group, @comment) %> |
<%= link_to 'Delete', group_comment_path(@comment.group, @comment), method: :delete %> |
<%= link_to 'Back', group_comments_path(@comment.group) %>