config/routes.rb
Rails.application.routes.draw do

  resources :groups do
	resources :comments do
		match 'bookpage/:bookpage', to: 'comments#bookpage', via: 'get', on: :collection, as: :page
	end
  end

  resources :user_groups, only: [:create, :destroy, :edit, :update]
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root 'static_pages#home'

  match '/help',    to: 'static_pages#help',    via: 'get'

  match '/about',   to: 'static_pages#about',   via: 'get'

  match '/contact', to: 'static_pages#contact', via: 'get'
  
  match '/signup',  to: 'users#new',            via: 'get'

  match '/signin',  to: 'sessions#new',		via: 'get'

  match '/signout', to: 'sessions#destroy', 	via: 'delete'
  post  'modal' => 'user_groups#modal'

end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :user_groups, dependent: :destroy
	has_many :users, :through => :user_groups
	
	has_many :comments, dependent: :destroy

	validates :name, presence: true, length: { maximum: 50 }, uniqueness: true
	validates :book_name, presence: true
	validates :page_number, presence: true, numericality: { greater_than: 0}
	validates :description, presence: true, length: {maximum: 1000}
	validates :num_to_read, presence: true, numericality: { greater_than_or_equal_to: 0}
	validate :start_date_not_later_than_end_date
	validate :num_to_read_less_than_num_pages

	def start_date_not_later_than_end_date
		if Date.today > end_date
			errors.add(:end_date, "^End date is in the past!")
		end
		#if start_date.past?
		#	errors.add(:start_date, "^Start date is in past!")
		#end
		if start_date > end_date
			errors.add(:start_date, "^Start date cannot be later than end date")
		end
	end

	def num_to_read_less_than_num_pages
		if num_to_read > page_number
			errors.add(:num_to_read, "^Read to page number must be less than or equal to number of pages")
		end
	end

	def self.search(query)
		where("lower(name) like ?", "%#{query.downcase}%")
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	# UserGroup
	has_many :user_groups, dependent: :destroy
	has_many :groups, :through => :user_groups
	has_many :comments
        
	before_save do
                self.email = email.downcase
		self.login = login.downcase
        end

	VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
	VALID_NAME_REGEX = /\A\w+\Z/i

	before_create :create_remember_token

	validates :name, presence: true, length: { maximum: 50 }
	validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: { case_sensitive: false }, confirmation: true
	validates :email_confirmation, presence: true
	validates :login, presence: true, format: {with: VALID_NAME_REGEX, message: "Only characters and digits"}, uniqueness: { case_sensitive: false }

	validates :password, presence: true, length: {minimum: 8}
	validates :password_confirmation, presence: true

	has_secure_password

        def User.new_remember_token
                SecureRandom.urlsafe_base64
        end

        def User.digest(token)
                Digest::SHA1.hexdigest(token.to_s)
        end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
	
end

app/controllers/groups_controller.rb
require "will_paginate/array"

class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user, only: [:new, :edit, :update, :destroy, :create]
  before_action :admin_user_for_group, only: [:edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
	if params.has_key?(:search)
		@groups = Group.search(params[:search]).paginate(page: params[:page], per_page: 10)
	else
    		@groups = Group.paginate(page: params[:page], per_page: 10) #order: 'name ASC'
	end
	#respond_to do |format|
	#	format.js {}
	#	format.html {}
	#end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
	current_page = 1
	if params[:page]
		 current_page =  params[:page]
	end
	per_page = 7
	if signed_in?	
		@group_users = @group.users.paginate(:page => current_page, :per_page=>per_page)
		#@group_users = WillPaginate::Collection.create(  current_page, per_page, @group.users.length) do |pager|
			#pager.replace @group.users #.where('user_id not in (?)', current_user.id)
		#end

		#@comment = @group.comments.build

		@top_comments = @group.comments.order(created_at: :desc).limit(10)
		@comment_pages = {}
		pgs = @group.comments.select('page_number')
		pgs.each do |p|
			@comment_pages[p.page_number] = true
		end
	end
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @group.admin_id = current_user.id
    respond_to do |format|
      if @group.save
	UserGroup.create(admin: true, user_id: current_user.id, group_id: @group.id)
	flash[:success] = "Group was successfully created!"
        format.html { redirect_to @group }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      flash[:success] = "Group successfully deleted"
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :book_name, :page_number, :description, :start_date, :end_date, :num_to_read)
    end

    def signed_in_user
	unless signed_in?
		store_location
		redirect_to signin_url, notice: "You must sign in to do that!"
	end
    end

    def admin_user_for_group
	am_i_admin = UserGroup.where('user_id in (?) and group_id in (?) and admin in (?)', current_user.id, @group.id, true)
	unless am_i_admin.any?
		store_location
		redirect_to user_path(current_user), notice: "You are not allowed to do that!"
	end
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :book_name %><br>
    <%= f.text_field :book_name %>
  </div>
  <div class="field">
    <%= f.label :page_number %><br>
    <%= f.number_field :page_number %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<tr>
	<td> <%= link_to group.name, group_path(group) %> </td>
	<td> <%= group.book_name %> </td>
	<% des = group.description %>
	<td> 
		<%= des[0..50] %> <% if des.length >= 50 %>...<% end %> 
	</td>
	<td> <%= group.page_number %></td>
	<!-- td> <%#= group.start_date %> </td -->
	<!-- td> <%#= group.end_date %> </td -->
	<td> <%= group.users.count %> </td>
	<% @group_admin = User.find( group.admin_id ) %>
	<td> <%= link_to @group_admin.login, user_path( @group_admin ) %> </td>
	<td> 
		<%= render 'group_controls', group: group, group_admin: @group_admin %>
	</td>
</tr>

app/views/groups/_group_controls.html.erb
<% if signed_in? %>
	<% user_group = UserGroup.where( 'user_id in (?) and group_id in (?)', current_user.id, group.id) %>
	<% if group_admin.id == current_user.id %>
		<%= link_to 'Edit <i class="icon-pencil "></i>'.html_safe, edit_group_path(group), class: "btn btn-mini ", style:"width: 50px" %>
		<%= link_to 'Delete <i class="icon-trash icon-white"></i>'.html_safe, group, method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-danger btn-mini" , style:"width: 50px"%>
		
	<% elsif user_group.count == 0 %>
	  <%= form_for(:user_group, url: user_groups_path) do |f| %>
		<%= hidden_field_tag :group_id, group.id  %>
		<%= button_tag(type: "submit", class: "btn btn-mini btn-success") do %>
				&nbsp;&nbsp;Join &nbsp;<i class="icon-plus icon-white"></i>&nbsp;&nbsp;
		<% end %>
	  <% end %>
	<% else %>
	  <%= link_to 'Leave <i class="icon-minus icon-white"></i>'.html_safe, user_group[0], method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-danger btn-mini", style:"width: 50px" %>
	<% end %>
<% end %>

app/views/groups/edit.html.erb
<% provide(:title, "Edit group") %>
<h1>Edit group</h1>
<div class="row">
	<div class="span4 offset4">
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
	<div class="alert alert-error">
      The form contains <%= pluralize(@group.errors.count, "error") %>
	</div>
      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", placeholder:"Group name", required: true, autofocus:true %>
  
    <%= f.label :book_name %>
    <%= f.text_field :book_name, class: "form-control", placeholder:"Book name", required: true %>

    <%= f.label :page_number, "Number of pages" %>
    <%= f.number_field :page_number, class: "form-control", placeholder:"400", required: true %>

    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", placeholder:"Short Description ( maximum 1000 characters ) of the book ... ", required: true %>

    <%= f.label :start_date %>
    <%= f.date_select :start_date %>

    <%= f.label :end_date %>
    <%= f.date_select :end_date %>
	
	<%= f.label :num_to_read, "Read to page number" %>
	<%= f.number_field :num_to_read, class: "form-control", placeholder:"400", required: true %>

    <%= f.submit "Update this group", class: "btn btn-large btn-primary btn-block" %>
<% end %>

<%= link_to 'Show', @group %> |
<%= link_to 'Groups', groups_path %> | <%= link_to 'Delete <i class="icon-trash icon-white"></i>'.html_safe, @group, method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-primary btn-danger" %>
  </div>
</div>

app/views/groups/index.html.erb
<% provide(:title, "All Groups") %>

    <% if @groups.any? %>
	 <div class="row"> 
	  <div class="span4 offset1">
	  <%= form_tag groups_path, :method => :get, remote: true, class: "form-horizontal form-inline form-search", role:"form" do %>
		<div class="form-group">
		    <!-- %= label_tag :search, "Name" % --> 
		    <%= text_field_tag :search, params[:search], class: "input-large search-query", placeholder: "Search group name" %>
		    <!-- %= submit_tag "Search", :name => nil, class: "form-control btn btn-info" % -->
		</div>
	  <% end %>
	  </div>
	 </div>
<div class="row">
  <div class="span12">
	  <%= will_paginate %>
		<h1> All groups </h1>
			<table class="table table-striped table-hover table-condensed">
				<thead>
					<tr>
						<th> Name </th>
						<th> Book </th>
						<th> Description </th>
						<th> #pages </th>
						<!-- th> Start date </th -->
						<!-- th> End date </th -->
						<th> #members </th>
						<th> Owner </th>
						<th> </th>
					</tr>
				</thead>
				<tbody id="groups">
				
			<!-- ul class="groups" -->
					<%= render @groups %>
			<!-- /ul -->
				</tbody>
			</table>

	  <%= will_paginate %>
  </div>
</div>
<% end %>

<div style="margin-top: 20px">
<%= link_to 'New Group', new_group_path, class:"btn btn-success btn-primary" %>
</div>

app/views/groups/index.js.erb
$("#groups").html("<%= escape_javascript(render(@groups)) %>");

app/views/groups/new.html.erb
<% provide(:title, "New group") %>
<h1>New group</h1>
<div class="row">
	<div class="span4 offset4">
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
	<div class="alert alert-error">
      The form contains <%= pluralize(@group.errors.count, "error") %>
	</div>
      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", placeholder:"Group name", required: true, autofocus:true %>
  
    <%= f.label :book_name %>
    <%= f.text_field :book_name, class: "form-control", placeholder:"Book name", required: true %>

    <%= f.label :page_number, "Number of pages" %>
    <%= f.number_field :page_number, class: "form-control", placeholder:"400", required: true %>

    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", placeholder:"Short Description ( maximum 1000 characters ) of the book ... ", required: true %>

    <%= f.label :start_date %>
    <%= f.date_select :start_date %>

    <%= f.label :end_date %>
    <%= f.date_select :end_date %>
	
	<%= f.label :num_to_read, "Read to page number" %>
	<%= f.number_field :num_to_read, class: "form-control", placeholder:"400", required: true %>

    <%= f.submit "Create this group", class: "btn btn-large btn-primary btn-block" %>
<% end %>
<%= link_to 'Cancel', groups_path %>
  </div>
</div>

app/views/groups/show.html.erb
<% provide(:title, @group.name) %>
<div class="row">
   <aside class="span4">
    <section>
	<h1>
	  <%= @group.name %>
	</h1>
	<p> <strong>Book:</strong>
	  <%= @group.book_name %>
	  <br/>
	  <b>pages:</b>
	  <%= @group.page_number %>
	</p>

	<p>
  	  <strong>Start date:</strong>
  	  <%= @group.start_date %>
	</p>

	<p>
  	  <strong>End date:</strong>
  	  <%= @group.end_date %>
	</p>
	<p>
	  <strong>milestone:</strong>
	  <%= @group.num_to_read %>/<b><%= @group.page_number %></b>
	</p>
	<p>
	  <% owner = User.find( @group.admin_id) %>
	  <strong> owner:</strong>
	  <%= owner.login %>
	</p>

    </section>
  </aside>

<div class="span6">
<p>
  <strong>Description:</strong>
  <%= @group.description %>
</p>
</div>
</div>
<% if signed_in? %>
 <% if current_user.group_ids.include?(@group.id) %>
 <% if @group_users.any? %>
<script type="text/javascript">
var my_fun = function(a)
{
	$('#bookpage').attr( 'value', a);
        $('#myModal').modal('show');
}
</script>
  <div class="row">
   <center><h3>Users</h3><br/></center>
   <%= will_paginate @group_users %>
   <div class="span10 offset1">
	<table class="table table-striped table-hover table-condensed">
		<thead>
			<tr>
				<th> Username </th>
				<th> Read pages </th>
			</tr>
		</thead>
		
		<tbody>
			
				<tr>
					<td>
						
					</td>
					<td>
						<div id="mainslider" data-toggle="tooltip" data-placement="right" trigger="manual" title="Page: <%= @group.num_to_read%>, due on: <%= @group.end_date%>"></div>
						<script type="text/javascript">
							$('#mainslider').tooltip().eq(0).tooltip('show').tooltip('disable').on('mouseout',function(){ $(this).tooltip('enable');});
							bookSlider('#mainslider', <%= @group.page_number %>, 20, true, <%= @group.num_to_read %>, true, <%= @comment_pages.to_json.html_safe %>, my_fun );
						</script>
					</td>
				</tr>
				<tr>
					<td>
						<%= gravatar_for current_user, size: 52 %>
						<%= link_to current_user.login, current_user %>
					</td>
					<td>
						<% user_group = UserGroup.where(' user_id in (?) and group_id in (?)', current_user.id, @group.id) %>
						<!-- %= link_to user_group[0].num_read, edit_user_group_path(user_group[0]) % -->
						<div id="ug<%= user_group[0].id %>" data-toggle="tooltip" data-placement="right" trigger="manual" title="<%= pluralize(user_group[0].num_read, 'page')%> read"></div>
						<script type="text/javascript">
							$('#ug<%= user_group[0].id %>').tooltip();
							bookSlider('#ug<%= user_group[0].id %>', <%= @group.page_number %>, 20, true, <%= user_group[0].num_read %>, false, [], my_fun );
						</script>
					</td>
				</tr>	
			<% @group_users.each do |user| %>
			 <% if user.id != current_user.id %>
				<tr>
				 <td>
					<%= gravatar_for user, size: 52 %>
					<%= link_to user.login, user %>
				 </td>
				 <td>
					<% user_group = UserGroup.where(' user_id in (?) and group_id in (?)', user.id, @group.id) %>
					<!-- %= link_to user_group[0].num_read, edit_user_group_path(user_group[0]) % -->
					<div id="ug<%= user_group[0].id %>" data-toggle="tooltip" data-placement="right" trigger="manual" title="<%= pluralize(user_group[0].num_read, 'page') %> read"></div>
					<script type="text/javascript">
						$('#ug<%= user_group[0].id %>').tooltip();
						bookSlider('#ug<%= user_group[0].id %>', <%= @group.page_number %>, 20, true, <%= user_group[0].num_read %>, false, [], my_fun );
					</script>
				 </td>
				</tr>	
			 <% end %>	
			<% end %>	
		</tbody>
		
	</table>	
   </div>
   <%= will_paginate @group_users%>
  </div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" hidden="true"> 
 <div class="modal-dialog"> 
  <div class="modal-content"> 
   <div class="modal-header"> 
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"> &times; </button> 
    <h4 class="modal-title" id="myModalLabel"> Choose an action</h4> 
   </div> 
<%= form_tag :controller => :user_groups, :action => :modal, :method => :post do %>
	<% user_group = UserGroup.where(' user_id in (?) and group_id in (?)', current_user.id, @group.id) %>

	<%= hidden_field_tag :user_group_id, user_group[0].id %>
   <div class="modal-body">
	<%= label_tag :bookpage, "page" %>
	<%= number_field_tag :bookpage, "1", class: "form-control", id: "bookpage" %>
	<%= label_tag :todo, "action" %>
	<% if current_user.id == @group.admin_id %>
	 <%= select_tag :todo, options_for_select([["Set your read number of pages","read"],["View comments","comments"],["Set group milestone","milestone"]]) %>
	 <%= label_tag :end_date, "Until" %>
	 <%= select_date Date.today, prefix: :end_date %>
	<% else %>
	 <%= select_tag :todo, options_for_select([["Set your read number of pages","read"],["View comments","comments"]]) %>
	<% end %>
   </div> 
   <div class="modal-footer"> 
    <button type="button" class="btn btn-default" data-dismiss="modal">Close </button> 
    <%= submit_tag "Ok", :name=>nil, class: "form-control btn btn-primary" %>
   </div> 
<% end %>

  </div><!-- /.modal-content --> 
 </div><!-- /.modal -->
</div>


 <% end %>
 

 
  
	
  <% @comment = @group.comments.build %>
  <%= render 'comments/form' %>

  <%= render 'comments/show_comments', comments: @top_comments %>

  <%= link_to 'All comments', group_comments_path(@group), class: "btn btn-info btn-primary" %><br><br>
 <% end %>
  <%= render 'group_controls', group: @group, group_admin: owner %><br><br>
<% end %>